runtime: nodejs
env: flex
manual_scaling:
  instances: 8
# Update with Serverless VPC Access connector details
 
# handlers:
# - url: /.*
#  script: auto
#Redis env variables
# env_variables:
#   REDISHOST: '10.64.193.60'
#   REDISPORT: '6379'
# # Update with Redis instance network name
# network:
#   name: default
